(draft) new BitVector implementation
NgaiJustin/btor2i pull request #4
Opened 2023-11-21 21:21 UTC by SanjitBasker

2023-11-21 22:33 UTC, NgaiJustin approved these changes
Looks good, feel free to merge publish once the bvec sub is fixed. Also left some comments

2023-11-21 22:33 UTC, NgaiJustin commented on Cargo.toml
>  bitvector = "0.1.5"
Remember to also remove the now deprecated `bitvector` crate

2023-11-21 22:33 UTC, NgaiJustin commented on src/bvec.rs
> +  //   bits: BVec,
Remove

2023-11-21 22:33 UTC, NgaiJustin commented on src/bvec.rs
> +    println!("{}", bv_7.bits);
Could also consider implementing the `Display` trait for our `bvec` struct

2023-11-23 02:15 UTC, NgaiJustin requested changes
Missed some stuff in the previous review, please fix before merging ty!

2023-11-23 02:15 UTC, NgaiJustin commented on src/bvec.rs
>    width: usize,
Also, this `width` field seems a bit silly since you can just access `bits.len()`
<img width="791" alt="Screenshot 2023-11-22 at 9 01 39 pm" src="https://github.com/NgaiJustin/btor2i/assets/57964367/48b4ac31-7fb0-41cf-a448-835e1b57ab43">

2023-11-23 02:15 UTC, NgaiJustin commented on src/bvec.rs
>    width: usize,
Since you haven't merged this yet, I would suggest you remove this and update the instances throughout.

2023-11-23 02:15 UTC, NgaiJustin commented on src/bvec.rs
> +  bits: BitVec<u8, Msb0>,
I missed this the first time round, but this should be `bits: BitVec<usize, Msb0>`. Also are you sure we want `Msb0` instead of `Lsb0` here?

2023-11-23 02:15 UTC, NgaiJustin commented on src/bvec.rs
>        width: bits.len(),
Yeah, width doesn't really provide any value anywhere.

2023-11-23 02:15 UTC, NgaiJustin commented on src/bvec.rs
This can be framed as an implementation of the `std::convert::From` trait instead as a public function of the struct. I would also add an implementation from usize since that's the defacto input we are going with (for now at least)

2023-11-23 02:15 UTC, NgaiJustin commented on src/bvec.rs
Here's a quick patch I added so I could move forward in another branch, I would suggest something like this but you can also explore other implementations. As long as we have some convenient way to turn an usize into a BitVector I'm happy.

```
impl From<usize> for BitVector {
  fn from(i: usize) -> Self {
    let bitvec = BitVec::from_element(i);
    BitVector {
      width: bitvec.len(),
      bits: bitvec,
    }
  }
}
```

2023-11-23 02:15 UTC, NgaiJustin commented on src/bvec.rs
Of course it'll look a bit different after you remove the `width` parameter.

2023-11-23 02:15 UTC, NgaiJustin commented on src/bvec.rs
> +    let bits = bv.bits.clone();
Why do you need to clone here?

2023-11-23 02:15 UTC, NgaiJustin commented on src/bvec.rs
> +    let mut other_vec = BitVec::new();
Since you haven't merged this yet, could you add some documentation for what some of these less obvious functions and parameters mean. For example, it's not immediately obvious what `l` and `u` are.

2023-11-23 02:15 UTC, NgaiJustin commented on src/bvec.rs
>    pub fn inc(bv: &BitVector) -> Self {
doc

2023-11-23 02:15 UTC, NgaiJustin commented on src/bvec.rs
> +    if bv1.bits.count_ones() != bv2.bits.count_ones() {
Why is this step necessary if you are going to iterate pairwise anyways? Also I'm pretty sure `bitvec` already has a `.eq` function. You might want to double check what `bitvec` already implements first
<img width="866" alt="Screenshot 2023-11-22 at 9 14 10 pm" src="https://github.com/NgaiJustin/btor2i/assets/57964367/5fad13ce-f3ce-462f-82cb-2af1c08297f4">

2023-11-24 02:43 UTC, SanjitBasker commented on src/bvec.rs
> +    let bits = bv.bits.clone();
rewrote most of the ops to use bit-slices and eliminate clones. had this as a TODO for a while

2023-11-24 02:51 UTC, SanjitBasker commented on src/bvec.rs
> +    if bv1.bits.count_ones() != bv2.bits.count_ones() {
Consider the set of indices where the bitvector is 1 as a set. When comparing for equality of two sets you can check $A\subseteq B$ and $B\subseteq A$, or you can check $|A|=|B|$ and $A\subseteq B$. I'm fairly confident that the second will be faster.

Maybe this is a bit silly but I could not find documentation describing the behavior of `==` and `!=` when comparing two bit-vectors of non-equal length. They also have `>=` and other comparison operators.

2023-11-24 02:55 UTC, SanjitBasker commented on src/bvec.rs
> +    println!("{}", bv_7.bits);
cool

2023-11-24 17:57 UTC, NgaiJustin approved these changes

2023-11-24 17:57 UTC, merged